
import { PersianLetter } from './types';

export const PERSIAN_ALPHABET: PersianLetter[] = [
  { char: 'آ', name: 'آ اول', example: 'آب', color: 'bg-red-400', imageUrl: 'https://picsum.photos/seed/water/200' },
  { char: 'ا', name: 'الف', example: 'اسب', color: 'bg-blue-400', imageUrl: 'https://picsum.photos/seed/horse/200' },
  { char: 'ب', name: 'ب', example: 'بستنی', color: 'bg-green-400', imageUrl: 'https://picsum.photos/seed/icecream/200' },
  { char: 'پ', name: 'پ', example: 'پروانه', color: 'bg-pink-400', imageUrl: 'https://picsum.photos/seed/butterfly/200' },
  { char: 'ت', name: 'ت', example: 'توپ', color: 'bg-yellow-400', imageUrl: 'https://picsum.photos/seed/ball/200' },
  { char: 'ث', name: 'ث', example: 'ثروت', color: 'bg-purple-400', imageUrl: 'https://picsum.photos/seed/treasure/200' },
  { char: 'ج', name: 'ج', example: 'جوجه', color: 'bg-orange-400', imageUrl: 'https://picsum.photos/seed/chick/200' },
  { char: 'چ', name: 'چ', example: 'چتر', color: 'bg-indigo-400', imageUrl: 'https://picsum.photos/seed/umbrella/200' },
  { char: 'ح', name: 'ح', example: 'حوض', color: 'bg-teal-400', imageUrl: 'https://picsum.photos/seed/pond/200' },
  { char: 'خ', name: 'خ', example: 'خرگوش', color: 'bg-emerald-400', imageUrl: 'https://picsum.photos/seed/rabbit/200' },
  { char: 'د', name: 'د', example: 'درخت', color: 'bg-lime-400', imageUrl: 'https://picsum.photos/seed/tree/200' },
  { char: 'ذ', name: 'ذ', example: 'ذرت', color: 'bg-yellow-600', imageUrl: 'https://picsum.photos/seed/corn/200' },
  { char: 'ر', name: 'ر', example: 'رنگین‌کمان', color: 'bg-cyan-400', imageUrl: 'https://picsum.photos/seed/rainbow/200' },
  { char: 'ز', name: 'ز', example: 'زرافه', color: 'bg-amber-400', imageUrl: 'https://picsum.photos/seed/giraffe/200' },
  { char: 'ژ', name: 'ژ', example: 'ژله', color: 'bg-rose-400', imageUrl: 'https://picsum.photos/seed/jelly/200' },
  { char: 'س', name: 'س', example: 'سیب', color: 'bg-red-500', imageUrl: 'https://picsum.photos/seed/apple/200' },
  { char: 'ش', name: 'ش', example: 'شیر', color: 'bg-yellow-700', imageUrl: 'https://picsum.photos/seed/lion/200' },
  { char: 'ص', name: 'ص', example: 'صورت', color: 'bg-orange-200', imageUrl: 'https://picsum.photos/seed/face/200' },
  { char: 'ض', name: 'ض', example: 'ضبط', color: 'bg-gray-400', imageUrl: 'https://picsum.photos/seed/record/200' },
  { char: 'ط', name: 'ط', example: 'طوطی', color: 'bg-green-600', imageUrl: 'https://picsum.photos/seed/parrot/200' },
  { char: 'ظ', name: 'ظ', example: 'ظرف', color: 'bg-slate-400', imageUrl: 'https://picsum.photos/seed/dishes/200' },
  { char: 'ع', name: 'ع', example: 'عینک', color: 'bg-sky-400', imageUrl: 'https://picsum.photos/seed/glasses/200' },
  { char: 'غ', name: 'غ', example: 'غذا', color: 'bg-orange-500', imageUrl: 'https://picsum.photos/seed/food/200' },
  { char: 'ف', name: 'ف', example: 'فیل', color: 'bg-blue-300', imageUrl: 'https://picsum.photos/seed/elephant/200' },
  { char: 'ق', name: 'ق', example: 'قایق', color: 'bg-blue-600', imageUrl: 'https://picsum.photos/seed/boat/200' },
  { char: 'ک', name: 'ک', example: 'کتاب', color: 'bg-amber-600', imageUrl: 'https://picsum.photos/seed/book/200' },
  { char: 'گ', name: 'گ', example: 'گل', color: 'bg-pink-600', imageUrl: 'https://picsum.photos/seed/flower/200' },
  { char: 'ل', name: 'ل', example: 'لک‌لک', color: 'bg-slate-200', imageUrl: 'https://picsum.photos/seed/stork/200' },
  { char: 'م', name: 'م', example: 'ماهی', color: 'bg-orange-300', imageUrl: 'https://picsum.photos/seed/fish/200' },
  { char: 'ن', name: 'ن', example: 'نان', color: 'bg-yellow-100', imageUrl: 'https://picsum.photos/seed/bread/200' },
  { char: 'و', name: 'و', example: 'ورزش', color: 'bg-indigo-300', imageUrl: 'https://picsum.photos/seed/sport/200' },
  { char: 'ه', name: 'ه', example: 'هلو', color: 'bg-orange-400', imageUrl: 'https://picsum.photos/seed/peach/200' },
  { char: 'ی', name: 'ی', example: 'یاس', color: 'bg-white', imageUrl: 'https://picsum.photos/seed/jasmine/200' },
];
